# Generated by Django 5.1.2 on 2024-10-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
