# Generated by Django 5.1.2 on 2024-10-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='text',
        ),
    ]
