# Generated by Django 5.1.2 on 2024-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_portfolio_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='image_one',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_six',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
