# Generated by Django 5.1.2 on 2024-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_portfolio_image_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_one',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
