# Generated by Django 5.1.2 on 2024-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_portfolio_image_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_five',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_four',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_one',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_six',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_three',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_two',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
