# Generated by Django 5.1.2 on 2024-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_portfolio_image_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image_one',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_five',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_four',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_six',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_three',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_two',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
