# Generated by Django 5.1.2 on 2024-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_portfolio_image_one_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_four',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_six',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_three',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_two',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
